"""Integration tests for the MVP flow.

Covers the full lifecycle:
  1. Create a task and verify the compound JSON response.
  2. Roll back a finding and assert the markdown changes.
  3. Verify cryptographic integrity via the /verify endpoint.
  4. Close a session and confirm the cleanup schedule.
  5. Edge cases: 404 on missing session, rollback of non-existent finding.
"""

import pytest
from fastapi.testclient import TestClient

from app.main import app


# ---------------------------------------------------------------------------
# fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def client() -> TestClient:
    """Factory-fresh TestClient per test for isolation."""
    return TestClient(app)


def _create_task(client: TestClient, user_id: str, prompt: str) -> dict:
    """Helper: POST /api/v1/tasks and return the parsed JSON body."""
    resp = client.post(
        "/api/v1/tasks",
        json={
            "user_id": user_id,
            "prompt": prompt,
            "cleanup_delay_seconds": 3600,
        },
    )
    assert resp.status_code == 200, resp.text
    return resp.json()


# ---------------------------------------------------------------------------
# 1. basic task creation & response shape
# ---------------------------------------------------------------------------


def test_create_task_returns_compound_response(client: TestClient) -> None:
    """The API must return a JSON compound response matching the schema in
    ``api_response.py``."""
    data = _create_task(client, "user001", "Test auditable MVP flow")

    # -- structure
    assert "session_id" in data
    assert len(data["markdown_content"]) > 0

    # -- audit metadata
    audit = data["audit_metadata"]
    assert audit["event_count"] >= 5
    assert audit["merkle_root"].startswith("sha256:")
    assert audit["content_signature"].startswith("hmac:")
    assert len(audit["findings"]) >= 2
    assert len(audit["cost_breakdown"]) >= 1

    # -- lineage
    assert "nodes" in data["lineage_data"]
    assert "edges" in data["lineage_data"]
    assert len(data["lineage_data"]["edges"]) >= 1

    # -- rollback
    assert len(data["rollback_options"]["rollbackable_findings"]) >= 1


# ---------------------------------------------------------------------------
# 2. rollback — markdown must change
# ---------------------------------------------------------------------------


def test_rollback_changes_markdown(client: TestClient) -> None:
    """When a finding is rolled back, the markdown must be regenerated by
    the RollbackController and differ from the original synthesis."""
    data = _create_task(client, "user002", "Rollback test — markdown change")

    session_id = data["session_id"]
    original_markdown = data["markdown_content"]
    rollbackable = data["rollback_options"]["rollbackable_findings"]
    assert len(rollbackable) >= 1

    finding_id = rollbackable[0]
    rollback_resp = client.post(
        f"/api/v1/sessions/{session_id}/rollback",
        json={"finding_id": finding_id, "reason": "integration test"},
    )
    assert rollback_resp.status_code == 200, rollback_resp.text
    rolled = rollback_resp.json()

    # -- markdown must have changed (regenerated, not just the original)
    assert rolled["markdown_content"] != original_markdown
    assert "Rollback Notice" in rolled["markdown_content"]
    assert "rolled back" in rolled["markdown_content"].lower()

    # -- the rolled-back finding is no longer rollbackable
    assert finding_id not in rolled["rollback_options"]["rollbackable_findings"]

    # -- event count grew (compensation + restore events)
    assert rolled["audit_metadata"]["event_count"] >= data["audit_metadata"]["event_count"] + 2


def test_rollback_preserves_session_id(client: TestClient) -> None:
    """Rollback must return the same session_id as the original task."""
    data = _create_task(client, "user003", "Session ID test")
    session_id = data["session_id"]
    finding_id = data["rollback_options"]["rollbackable_findings"][0]

    rolled = client.post(
        f"/api/v1/sessions/{session_id}/rollback",
        json={"finding_id": finding_id, "reason": "test"},
    ).json()

    assert rolled["session_id"] == session_id


# ---------------------------------------------------------------------------
# 3. integrity verification
# ---------------------------------------------------------------------------


def test_verify_endpoint_returns_valid(client: TestClient) -> None:
    """The /verify endpoint must recompute hashes and confirm the report is
    cryptographically intact."""
    data = _create_task(client, "user004", "Verification test")

    resp = client.post(
        f"/api/v1/sessions/{data['session_id']}/verify",
    )
    assert resp.status_code == 200, resp.text
    result = resp.json()

    assert result["session_id"] == data["session_id"]
    assert result["merkle_root"].startswith("sha256:")
    assert result["content_signature"].startswith("hmac:")
    assert result["event_count"] == data["audit_metadata"]["event_count"]


def test_verify_after_rollback_still_valid(client: TestClient) -> None:
    """Rollback writes new events — the verify endpoint should still see a
    valid chain because the SynthesisRestored event is included in the
    recomputed Merkle tree."""
    data = _create_task(client, "user005", "Verify after rollback test")
    finding_id = data["rollback_options"]["rollbackable_findings"][0]

    client.post(
        f"/api/v1/sessions/{data['session_id']}/rollback",
        json={"finding_id": finding_id, "reason": "verify test"},
    )

    resp = client.post(f"/api/v1/sessions/{data['session_id']}/verify")
    assert resp.status_code == 200
    result = resp.json()
    assert result["merkle_root"].startswith("sha256:")


# ---------------------------------------------------------------------------
# 4. session lifecycle
# ---------------------------------------------------------------------------


def test_close_session(client: TestClient) -> None:
    """Closing a session must return a confirmed status."""
    data = _create_task(client, "user006", "Close test")

    close_resp = client.post(
        f"/api/v1/sessions/{data['session_id']}/close",
    )
    assert close_resp.status_code == 200
    assert close_resp.json()["status"] == "scheduled_for_cleanup"


# ---------------------------------------------------------------------------
# 5. error handling & edge cases
# ---------------------------------------------------------------------------


def test_missing_session_returns_404(client: TestClient) -> None:
    """Rollback on a non-existent session returns 404."""
    resp = client.post(
        "/api/v1/sessions/nonexistent-sess/rollback",
        json={"finding_id": "f1", "reason": "test"},
    )
    assert resp.status_code == 404


def test_verify_missing_session_returns_404(client: TestClient) -> None:
    """Verify on a non-existent session returns 404."""
    resp = client.post("/api/v1/verify/simple", json={"session_id": "nonexistent-sess"})
    assert resp.status_code == 404


def test_rollback_nonexistent_finding_returns_gracefully(client: TestClient) -> None:
    """Rolling back a finding that does not exist in the session must not
    crash — the controller validates existence and returns current state."""
    data = _create_task(client, "user007", "Nonexistent finding test")

    resp = client.post(
        f"/api/v1/sessions/{data['session_id']}/rollback",
        json={"finding_id": "f_does_not_exist", "reason": "test"},
    )
    # The orchestrator catches RollbackError and returns 200 with current state
    assert resp.status_code == 200, resp.text
    # The rollbackable list should be unchanged
    result = resp.json()
    opts = result.get("rollback_options", {})
    rollbackable = opts.get("rollbackable_findings", [])
    assert len(rollbackable) >= 1
